# Generated by Django 3.2.3 on 2021-05-24 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('photo', models.ImageField(blank=True, default=None, upload_to='patients/patients_pics')),
                ('gender',
                 models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=32)),
                ('language',
                 models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='en', max_length=32)),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
